/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */

export interface BusinessCard {
  id: number;
  name: string;
  slug: string;
  categoryId: number;
  categoryName: string;
  city: string;
  coverImage?: string | null;
  logoImage?: string | null;
  rating: number;
  reviewCount: number;
  shortDescription?: string | null;
  hasActiveCampaign: boolean;
  activeCampaignDiscount?: number | null;
  subscriptionTier?: string | null;
}
