/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import type { CreateBusinessBodySocialLinks } from "./createBusinessBodySocialLinks";

export interface CreateBusinessBody {
  name: string;
  categoryId: number;
  description?: string | null;
  shortDescription?: string | null;
  address?: string | null;
  city: string;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  coverImage?: string | null;
  logoImage?: string | null;
  workingHours?: string | null;
  socialLinks?: CreateBusinessBodySocialLinks;
}
