/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary List all categories
 */
export const ListCategoriesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  icon: zod.string(),
  businessCount: zod.number(),
});
export const ListCategoriesResponse = zod.array(ListCategoriesResponseItem);

/**
 * @summary List businesses with filters
 */
export const listBusinessesQueryLimitDefault = 20;
export const listBusinessesQueryOffsetDefault = 0;

export const ListBusinessesQueryParams = zod.object({
  categoryId: zod.coerce.number().optional(),
  city: zod.coerce.string().optional(),
  minRating: zod.coerce.number().optional(),
  hasActiveCampaign: zod.coerce.boolean().optional(),
  search: zod.coerce.string().optional(),
  limit: zod.coerce.number().default(listBusinessesQueryLimitDefault),
  offset: zod.coerce.number().default(listBusinessesQueryOffsetDefault),
});

export const ListBusinessesResponse = zod.object({
  businesses: zod.array(
    zod.object({
      id: zod.number(),
      name: zod.string(),
      slug: zod.string(),
      categoryId: zod.number(),
      categoryName: zod.string(),
      city: zod.string(),
      coverImage: zod.string().nullish(),
      logoImage: zod.string().nullish(),
      rating: zod.number(),
      reviewCount: zod.number(),
      shortDescription: zod.string().nullish(),
      hasActiveCampaign: zod.boolean(),
      activeCampaignDiscount: zod.number().nullish(),
      subscriptionTier: zod.string().nullish(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Create a new business profile
 */
export const CreateBusinessBody = zod.object({
  name: zod.string(),
  categoryId: zod.number(),
  description: zod.string().nullish(),
  shortDescription: zod.string().nullish(),
  address: zod.string().nullish(),
  city: zod.string(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  website: zod.string().nullish(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  workingHours: zod.string().nullish(),
  socialLinks: zod.record(zod.string(), zod.string()).nullish(),
});

/**
 * @summary Get featured businesses for homepage
 */
export const GetFeaturedBusinessesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  categoryName: zod.string(),
  city: zod.string(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  shortDescription: zod.string().nullish(),
  hasActiveCampaign: zod.boolean(),
  activeCampaignDiscount: zod.number().nullish(),
  subscriptionTier: zod.string().nullish(),
});
export const GetFeaturedBusinessesResponse = zod.array(
  GetFeaturedBusinessesResponseItem,
);

/**
 * @summary Get the authenticated user's business
 */
export const GetMyBusinessResponse = zod.object({
  id: zod.number(),
  ownerId: zod.string(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  description: zod.string().nullish(),
  shortDescription: zod.string().nullish(),
  address: zod.string().nullish(),
  city: zod.string(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  website: zod.string().nullish(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  workingHours: zod.string().nullish(),
  socialLinks: zod.record(zod.string(), zod.string()).nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Get business detail
 */
export const GetBusinessParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBusinessResponse = zod
  .object({
    id: zod.number(),
    ownerId: zod.string(),
    name: zod.string(),
    slug: zod.string(),
    categoryId: zod.number(),
    description: zod.string().nullish(),
    shortDescription: zod.string().nullish(),
    address: zod.string().nullish(),
    city: zod.string(),
    phone: zod.string().nullish(),
    email: zod.string().nullish(),
    website: zod.string().nullish(),
    coverImage: zod.string().nullish(),
    logoImage: zod.string().nullish(),
    workingHours: zod.string().nullish(),
    socialLinks: zod.record(zod.string(), zod.string()).nullish(),
    rating: zod.number(),
    reviewCount: zod.number(),
    createdAt: zod.string(),
  })
  .and(
    zod.object({
      categoryName: zod.string(),
      activeCampaigns: zod.array(
        zod.object({
          id: zod.number(),
          businessId: zod.number(),
          title: zod.string(),
          description: zod.string().nullish(),
          discountPercent: zod.number(),
          startDate: zod.string(),
          endDate: zod.string(),
          isActive: zod.boolean(),
          createdAt: zod.string(),
        }),
      ),
    }),
  );

/**
 * @summary Update business profile
 */
export const UpdateBusinessParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateBusinessBody = zod.object({
  name: zod.string().optional(),
  categoryId: zod.number().optional(),
  description: zod.string().nullish(),
  shortDescription: zod.string().nullish(),
  address: zod.string().nullish(),
  city: zod.string().optional(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  website: zod.string().nullish(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  workingHours: zod.string().nullish(),
  socialLinks: zod.record(zod.string(), zod.string()).nullish(),
});

export const UpdateBusinessResponse = zod.object({
  id: zod.number(),
  ownerId: zod.string(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  description: zod.string().nullish(),
  shortDescription: zod.string().nullish(),
  address: zod.string().nullish(),
  city: zod.string(),
  phone: zod.string().nullish(),
  email: zod.string().nullish(),
  website: zod.string().nullish(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  workingHours: zod.string().nullish(),
  socialLinks: zod.record(zod.string(), zod.string()).nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  createdAt: zod.string(),
});

/**
 * @summary Get campaigns for a business
 */
export const GetBusinessCampaignsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBusinessCampaignsResponseItem = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  title: zod.string(),
  description: zod.string().nullish(),
  discountPercent: zod.number(),
  startDate: zod.string(),
  endDate: zod.string(),
  isActive: zod.boolean(),
  createdAt: zod.string(),
});
export const GetBusinessCampaignsResponse = zod.array(
  GetBusinessCampaignsResponseItem,
);

/**
 * @summary Get products/menu for a business
 */
export const GetBusinessProductsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBusinessProductsResponseItem = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  image: zod.string().nullish(),
  createdAt: zod.string(),
});
export const GetBusinessProductsResponse = zod.array(
  GetBusinessProductsResponseItem,
);

/**
 * @summary Get reviews for a business
 */
export const GetBusinessReviewsParams = zod.object({
  id: zod.coerce.number(),
});

export const GetBusinessReviewsResponseItem = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  userId: zod.string(),
  userName: zod.string(),
  rating: zod.number(),
  comment: zod.string().nullish(),
  createdAt: zod.string(),
});
export const GetBusinessReviewsResponse = zod.array(
  GetBusinessReviewsResponseItem,
);

/**
 * @summary Create a review for a business
 */
export const CreateReviewParams = zod.object({
  id: zod.coerce.number(),
});

export const createReviewBodyRatingMax = 5;

export const CreateReviewBody = zod.object({
  rating: zod.number().min(1).max(createReviewBodyRatingMax),
  comment: zod.string().nullish(),
});

/**
 * @summary List all active campaigns
 */
export const listCampaignsQueryLimitDefault = 20;
export const listCampaignsQueryOffsetDefault = 0;

export const ListCampaignsQueryParams = zod.object({
  limit: zod.coerce.number().default(listCampaignsQueryLimitDefault),
  offset: zod.coerce.number().default(listCampaignsQueryOffsetDefault),
});

export const ListCampaignsResponseItem = zod
  .object({
    id: zod.number(),
    businessId: zod.number(),
    title: zod.string(),
    description: zod.string().nullish(),
    discountPercent: zod.number(),
    startDate: zod.string(),
    endDate: zod.string(),
    isActive: zod.boolean(),
    createdAt: zod.string(),
  })
  .and(
    zod.object({
      businessName: zod.string(),
      businessCity: zod.string(),
      businessLogoImage: zod.string().nullish(),
    }),
  );
export const ListCampaignsResponse = zod.array(ListCampaignsResponseItem);

/**
 * @summary List campaigns for authenticated user's business
 */
export const ListMyCampaignsResponseItem = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  title: zod.string(),
  description: zod.string().nullish(),
  discountPercent: zod.number(),
  startDate: zod.string(),
  endDate: zod.string(),
  isActive: zod.boolean(),
  createdAt: zod.string(),
});
export const ListMyCampaignsResponse = zod.array(ListMyCampaignsResponseItem);

/**
 * @summary Create a campaign
 */
export const CreateCampaignBody = zod.object({
  title: zod.string(),
  description: zod.string().nullish(),
  discountPercent: zod.number(),
  startDate: zod.string(),
  endDate: zod.string(),
});

/**
 * @summary Update a campaign
 */
export const UpdateCampaignParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateCampaignBody = zod.object({
  title: zod.string().optional(),
  description: zod.string().nullish(),
  discountPercent: zod.number().optional(),
  startDate: zod.string().optional(),
  endDate: zod.string().optional(),
});

export const UpdateCampaignResponse = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  title: zod.string(),
  description: zod.string().nullish(),
  discountPercent: zod.number(),
  startDate: zod.string(),
  endDate: zod.string(),
  isActive: zod.boolean(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a campaign
 */
export const DeleteCampaignParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List products for authenticated user's business
 */
export const ListMyProductsResponseItem = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  image: zod.string().nullish(),
  createdAt: zod.string(),
});
export const ListMyProductsResponse = zod.array(ListMyProductsResponseItem);

/**
 * @summary Create a product
 */
export const CreateProductBody = zod.object({
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  image: zod.string().nullish(),
});

/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  id: zod.coerce.number(),
});

export const UpdateProductBody = zod.object({
  name: zod.string().optional(),
  description: zod.string().nullish(),
  price: zod.number().optional(),
  image: zod.string().nullish(),
});

export const UpdateProductResponse = zod.object({
  id: zod.number(),
  businessId: zod.number(),
  name: zod.string(),
  description: zod.string().nullish(),
  price: zod.number(),
  image: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  id: zod.coerce.number(),
});

/**
 * @summary List user's favorite businesses
 */
export const ListFavoritesResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  slug: zod.string(),
  categoryId: zod.number(),
  categoryName: zod.string(),
  city: zod.string(),
  coverImage: zod.string().nullish(),
  logoImage: zod.string().nullish(),
  rating: zod.number(),
  reviewCount: zod.number(),
  shortDescription: zod.string().nullish(),
  hasActiveCampaign: zod.boolean(),
  activeCampaignDiscount: zod.number().nullish(),
  subscriptionTier: zod.string().nullish(),
});
export const ListFavoritesResponse = zod.array(ListFavoritesResponseItem);

/**
 * @summary Add business to favorites
 */
export const AddFavoriteBody = zod.object({
  businessId: zod.number(),
});

/**
 * @summary Remove business from favorites
 */
export const RemoveFavoriteParams = zod.object({
  businessId: zod.coerce.number(),
});

/**
 * @summary List available subscription plans
 */
export const ListSubscriptionPlansResponseItem = zod.object({
  id: zod.number(),
  name: zod.string(),
  tier: zod.string(),
  priceMonthly: zod.number(),
  features: zod.array(zod.string()),
});
export const ListSubscriptionPlansResponse = zod.array(
  ListSubscriptionPlansResponseItem,
);

/**
 * @summary Get authenticated user's current subscription
 */
export const GetMySubscriptionResponse = zod.object({
  id: zod.number(),
  userId: zod.string(),
  planId: zod.number(),
  planName: zod.string(),
  tier: zod.string(),
  status: zod.string(),
  startDate: zod.string(),
  endDate: zod.string().nullish(),
  createdAt: zod.string(),
});

/**
 * @summary Subscribe to a plan
 */
export const SubscribeBody = zod.object({
  planId: zod.number(),
});

/**
 * @summary Get analytics for authenticated user's business
 */
export const GetMyAnalyticsResponse = zod.object({
  totalProfileViews: zod.number(),
  viewsThisMonth: zod.number(),
  viewsLastMonth: zod.number(),
  totalCampaignClicks: zod.number(),
  totalReviews: zod.number(),
  averageRating: zod.number(),
  totalProducts: zod.number(),
  totalCampaigns: zod.number(),
  dailyViews: zod.array(
    zod.object({
      date: zod.string(),
      count: zod.number(),
    }),
  ),
});

/**
 * @summary Record a profile view for a business
 */
export const RecordProfileViewBody = zod.object({
  businessId: zod.number(),
});
