/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */

export interface SubscriptionPlan {
  id: number;
  name: string;
  tier: string;
  priceMonthly: number;
  features: string[];
}
