/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import type { DailyViewCount } from "./dailyViewCount";

export interface BusinessAnalytics {
  totalProfileViews: number;
  viewsThisMonth: number;
  viewsLastMonth: number;
  totalCampaignClicks: number;
  totalReviews: number;
  averageRating: number;
  totalProducts: number;
  totalCampaigns: number;
  dailyViews: DailyViewCount[];
}
