/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Campaign } from "./campaign";

export type CampaignWithBusiness = Campaign & {
  businessName: string;
  businessCity: string;
  businessLogoImage?: string | null;
};
