/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */
import type { Business } from "./business";
import type { Campaign } from "./campaign";

export type BusinessDetail = Business & {
  categoryName: string;
  activeCampaigns: Campaign[];
};
