/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * MekanGo API specification
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateCampaignBody {
  title?: string;
  description?: string | null;
  discountPercent?: number;
  startDate?: string;
  endDate?: string;
}
